# Generated by Django 4.2.1 on 2023-05-22 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 5, 10, 10, 494094, tzinfo=datetime.timezone.utc)),
        ),
    ]
